### ISSUE TITLE
Releases URL doesn't have jars

### ISSUE THREAD

**Issue by EslamElHusseiny** [mwz/sonar-scala#94] opened 2018-08-08 13:34 UTC
Hi,
releases URL in the README https://github.com/mwz/sonar-scala/releases doesn't have links to jars.
I found them in https://dl.bintray.com/mwz/maven/com/github/mwz/sonar-scala_2.12/ instead.

**Comment by BalmungSan** [comment] 2018-08-08 13:57
Duplicate of #74

**Comment by EslamElHusseiny** [comment] 2018-08-08 14:05
Thanks @BalmungSan

**Closed** 2018-08-08 14:05 UTC
